### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Gerardo-Sista** [IvanPeevski/BlazorDemoSample#1]
Hello,
thank you for the sample.
But
- on start it's reall slow and showing a ugly empty menu with a square on page
- dark mode doesn't work
- there's no example on validation from model with "Required(ErrorMessage ="Field is mandatory")  DataAnnotation

Thank you

**Comment by IvanPeevski** [comment]
Hello Gerardo,

Thank you for the feedback. Please update the local version of the repository.

For the validation, you can see that all fields in the register form are mandatory. 
For example, if you select any of the inputs and then leave the input without writing anything, an error message will be displayed at the bottom of the form. 
Some of the other fields also have additional validation such as a validity check for the Email field.
The form cannot be submitted until all inputs are valid. 

Dark mode is now set as enabled by default. It can be disabled with the checkbox below the Welcome message. The dark mode of all smart components can be easily controlled by the value of the `theme` attribute of the `<body>` tag.

For your ease, a comparison of the light and dark modes:

![Light Mode](https://user-images.githubusercontent.com/37153196/180884807-d7d00f45-8c64-4bea-b580-bee3cc02c85d.png)
![Dark Mode](https://user-images.githubusercontent.com/37153196/180884353-51ae9f08-f7bd-4d35-939e-9477e565da7d.png)
